usr/bin/kteatime
usr/share/applications/kde4/kteatime.desktop
usr/share/kde4/apps/kteatime/kteatime.notifyrc
usr/share/kde4/apps/kteatime/hicolor/16x16/apps/kteatime.png
usr/share/kde4/apps/kteatime/hicolor/48x48/apps/kteatime.png
usr/share/kde4/apps/kteatime/hicolor/32x32/apps/kteatime.png

usr/share/doc/kde4/HTML/en/kteatime/index.cache.bz2
usr/share/doc/kde4/HTML/en/kteatime/index.docbook
usr/share/doc/kde4/HTML/en/kteatime/config.png
